### ISSUE TITLE
How do you host your maven?

### ISSUE THREAD

**Issue by BD103** [unascribed/AsyncSimpleLog#1]
Hi! (Sorry I know this issue isn't related to the project.)

I saw that you have your own Maven. How do you host it? I'm interested in creating my own Maven sense MavenCentral is overly complicated.

Thanks,
-BD103

**Comment by unascribed** [comment]
Static directory served by nginx on a server I rent from OVH.

There's nothing special about Maven, it's just a bunch of files in a particular structure with no dynamic content whatsoever. If you point Gradle's Maven publisher at an empty directory, it will create a Maven repo for you out of whole cloth.

**Comment by BD103** [comment]
Thank you!
